name: Publish Q-VIEW

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.PERSENAL_TOKEN }}
        run: |
          git config --global user.email "q7but@qq.com"
          git config --global user.name "NickBoomBoom"
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc
          npm i -g pnpm 
          pnpm i
          cd packages/q-view
          pnpm i
          pnpm version patch
          pnpm run publish
          new_version=$(jq -r .version package.json)
          git add .
          git commit -m "q-view new version: $new_version"
          git push
